baseUrl = ""
title = "Distill Hugo Theme"
author = "Sanyam Kapoor"
canonifyurls = true
theme = "signalskew-theme"

[taxonomies]
# TODO: Taxonomies?

staticDir = ['static']

[params]
  description = "Distill Hugo Theme Demo"
  keywords = ["hugo", "distill", "theme"]
  sourcePrefix = "https://github.com/activatedgeek/distillpub/blob/master/exampleSite"

  theme_color = "#0f2e3d"
  dark_mode_feature = true
  header_metadata = '<a rel="me" href="https://mastodon/@user"></a>'
  social_in_menu = false
  rss_in_menu = true

  [[params.social]]
  class = "fa-solid fa-user-graduate"
  url = "https://scholar.google.com/citations?user=p0NMtgsAAAAJ"
  alt = "Google Scholar"

  [[params.social]]
  class = "fa-brands fa-github"
  url = "https://github.com/activatedgeek"
  alt = "GitHub"

  [[params.social]]
  class = "fa-brands fa-hacker-news"
  url = "https://news.ycombinator.com/user?id=activatedgeek"
  alt = "Hacker News"

  [[params.social]]
  class = "fa-brands fa-linkedin"
  url = "https://linkedin.com/in/sanyamkapoor"
  alt = "LinkedIn"

  [[params.social]]
  class = "fab fa-stack-overflow"
  url = "https://stackoverflow.com/users/2425365"
  alt = "Stack Overflow"

  [[params.social]]
  class = "fab fa-twitter"
  url = "https://twitter.com/activatedgeek"
  alt = "Twitter"

[menu]

  [[menu.main]]
  identifier = "About"
  name = "About Hugo"
  title = "About"
  url = "/about"
  weight = -10
